# Generated by Django 5.0 on 2023-12-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='neighborhood',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
