# Generated by Django 5.0 on 2023-12-28 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, null=True)),
                ('neighborhood', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('daily_rate', models.PositiveIntegerField()),
                ('typ', models.CharField(choices=[('mariage', 'Mariage'), ('anniversaire', 'Anniversaire'), ('conference', 'Conference'), ('reunion', 'Reunion'), ('ceremonie', 'Ceremonie')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pending', models.BooleanField(default=False)),
                ('confirm_or_no', models.BooleanField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='event_room_managment.room')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images_de_sale')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='event_room_managment.room')),
            ],
        ),
    ]
