# Generated by Django 5.0 on 2024-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_room_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
